### ISSUE TITLE
[Doc] Could you also provide an example of how DocumentClient can be injected to write a query that could be fired on CosmosDB?

### ISSUE THREAD

**Issue by dmillwalla** [Microsoft/spring-data-documentdb#16]
Is there a way the DocumentClient can be used with Autowired annotation to use it to execute queries? Or in this case, using EntityManager with PersistenceContext annotation can be used to execute queries on CosmosDB?

Alternatively, does it make sense to create a wrapper class that serves a singleton DocumentClient instance in Spring instead?

**Comment by pyryjook** [comment]
Yes, this would be awesome addition to docs! 👍🏻

**Comment by yungez** [comment]
Hi @dmillwalla thanks for feedback. not sure I understand the usage correctly. 
1. Do you need an autowired DocumentClient to do query with the DocumentClient? If yes, you could use DocumentDB Spring Autoconfigure package at https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot, to autowire a DocumentClient, instead of this Spring Data package.
2. Or Do you need Spring data Custom query feature supported in this repo? 

Spring data for Azure documentdb is based on spring data. so we have repository support and template support.  pls share more detail on requirements.  thanks!

**Comment by dmillwalla** [comment]
@yungez 

Point #1 pretty much answers what I was seeking from this code sample. If you could expand this code sample by including this mechanism as well, it would be very helpful for anyone looking at this code sample.

Thanks for your prompt reply!

**Comment by yungez** [comment]
HI @dmillwalla  to use autowired DocumentClient:
1. add dependencies to package azure-documentdb, and azure-spring-boot, 

1. in code, just add
```
@Autowired
    private DocumentClient documentClient;
```

1. in your properties file, add cosmos db connection info:
```
azure.documentdb.uri=put-your-documentdb-uri-here
azure.documentdb.key=put-your-documentdb-key-here
azure.documentdb.database=put-your-documentdb-databasename-here
```

**Comment by dmillwalla** [comment]
Thanks a lot @yungez !
